server:
  port: 50000

spring:
  config:
    import: application-product.yml
  servlet:
    multipart:
      max-file-size: 5MB
  datasource:
    hikari:
      max-lifetime: 300000

mybatis:
  type-aliases-package: com.baioretto.wishbottle.bean
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true